# Generated by Django 4.2.1 on 2023-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('winner', models.BooleanField(default=False)),
                ('allstars', models.IntegerField()),
                ('winnerofallstars', models.BooleanField(default=False)),
                ('specialty', models.CharField(max_length=250)),
                ('instagramhandle', models.CharField(max_length=100)),
            ],
        ),
    ]
