# Generated by Django 4.2.1 on 2023-06-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_queen_allstars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queen',
            new_name='DragQueen',
        ),
    ]
