# Generated by Django 4.2.1 on 2023-06-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_queen_dragqueen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clothes', models.CharField(max_length=100)),
                ('wigs', models.CharField(max_length=100)),
                ('dragqueen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dragqueen')),
            ],
        ),
    ]
