# Generated by Django 4.2.1 on 2023-06-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_outfit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='wigs',
            new_name='wig',
        ),
    ]
