# Generated by Django 4.2.1 on 2023-06-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_wigs_outfit_wig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-date']},
        ),
    ]
