# Generated by Django 4.2.1 on 2023-06-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_outfit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={},
        ),
    ]
