# Generated by Django 4.2.1 on 2023-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_outfit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='makeup',
            field=models.CharField(default='Winged Eyeliner', max_length=100),
        ),
        migrations.AddField(
            model_name='outfit',
            name='nails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='clothes',
            field=models.CharField(default='Body Suit', max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='wig',
            field=models.CharField(default='Teased Blonde Wig', max_length=100),
        ),
    ]
