# Generated by Django 4.2.1 on 2023-06-05 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_outfit_makeup_outfit_nails_alter_outfit_clothes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
