# Generated by Django 4.2.1 on 2023-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_performance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='performance',
            name='time',
            field=models.CharField(default='8pm', max_length=10),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='website',
            field=models.URLField(blank=True, default='https://www.heartweho.com/', null=True),
        ),
    ]
