# Generated by Django 4.2.1 on 2023-06-05 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_outfit_options_performance_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
