# Generated by Django 4.2.1 on 2023-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_performance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='nameofshow',
            field=models.CharField(default='Planet Pride', max_length=200),
        ),
    ]
