# Generated by Django 4.2.1 on 2023-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_nameofshow_performance_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragqueen',
            name='performances',
            field=models.ManyToManyField(to='main_app.performance'),
        ),
    ]
