# Generated by Django 4.2.2 on 2023-06-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_outfit_makeup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='wig',
            field=models.CharField(blank=True, choices=[('Reveal Coat', 'Reveal Coat'), ('Blue Ostrich Feather Dress', 'Blue Ostrich Feather Dress'), ('Little Black Dress', 'Little Black Dress'), ('Magenta Body Suit', 'Magenta Body Suit'), ('Cheetah Dress', 'Cheetah Dress'), ('Transparent Neon Yellow Dress', 'Transparent Neon Yellow Dress'), ('Silver Goddess Dress', 'Silver Goddess Dress'), ('Mesh Corset Dress', 'Mesh Corset Dress'), ('Puff Sleeve Leopard Jacket', 'Puff Sleeve Leopard Jacket'), ('Red Hologram Jacket', 'Red Hologram Jacket'), ('Silver Sequin Dress', 'Silver Sequin Dress')], default='Reveal Coat', max_length=100, null=True),
        ),
    ]
