# Generated by Django 4.2.2 on 2023-06-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_outfit_wig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='clothes',
            field=models.CharField(blank=True, choices=[('Reveal Coat', 'Reveal Coat'), ('Blue Ostrich Feather Dress', 'Blue Ostrich Feather Dress'), ('Little Black Dress', 'Little Black Dress'), ('Magenta Body Suit', 'Magenta Body Suit'), ('Cheetah Dress', 'Cheetah Dress'), ('Transparent Neon Yellow Dress', 'Transparent Neon Yellow Dress'), ('Silver Goddess Dress', 'Silver Goddess Dress'), ('Mesh Corset Dress', 'Mesh Corset Dress'), ('Puff Sleeve Leopard Jacket', 'Puff Sleeve Leopard Jacket'), ('Red Hologram Jacket', 'Red Hologram Jacket'), ('Silver Sequin Dress', 'Silver Sequin Dress')], default='Reveal Coat', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='makeup',
            field=models.CharField(blank=True, choices=[('mascara', 'Mascara'), ('Face Primer', 'Face Primer'), ('Foundation', 'Foundation'), ('Highlighter', 'Highlighter'), ('Glue Stick', 'Glue Stick'), ('Red Eye Shadow', 'Red Eye Shadow'), ('Orange Eye Shadow', 'Orange Eye Shadow'), ('Yellow Eye Shadow', 'Yellow Eye Shadow'), ('Green Eye Shadow', 'Green Eye Shadow'), ('Blue Eye Shadow', 'Blue Eye Shadow'), ('Purple Eye Shadow', 'Purple Eye Shadow'), ('Eyeliner', 'Eyeliner'), ('Translucent Powder', 'Translucent Powder'), ('False Lashes', 'False Lashes'), ('Lip Liner', 'Lip Liner'), ('Red Lipstick', 'Red Lipstick'), ('Pink Lipstick', 'Pink Lipstick'), ('Black Lipstick', 'Black Lipstick'), ('Clear Gloss', 'Clear Gloss'), ('Pink Gloss', 'Pink Gloss'), ('Red Gloss', 'Red Gloss'), ('Blush', 'Blush'), ('Bronzer', 'Bronzer')], default='mascara', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='wig',
            field=models.CharField(default='Teased Blonde Wig', max_length=100),
        ),
    ]
