# Generated by Django 4.2.2 on 2023-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_outfit_wig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(verbose_name='Performance date'),
        ),
    ]
