# Generated by Django 4.2.2 on 2023-06-08 13:58

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_outfit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(default=main_app.models.get_default_date, verbose_name='Performance date'),
        ),
    ]
