# Generated by Django 4.2.2 on 2023-06-08 15:24

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_performance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragqueen',
            name='instagramhandle',
            field=models.CharField(default='thebiancadelrio', max_length=100),
        ),
        migrations.AlterField(
            model_name='dragqueen',
            name='name',
            field=models.CharField(default='Bianca', max_length=100),
        ),
        migrations.AlterField(
            model_name='dragqueen',
            name='season',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='dragqueen',
            name='specialty',
            field=models.CharField(default='Comedy', max_length=250),
        ),
        migrations.AlterField(
            model_name='dragqueen',
            name='winner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(default=main_app.models.get_default_date, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(default=main_app.models.get_default_date, verbose_name='Date'),
        ),
    ]
