# Generated by Django 4.2.2 on 2023-06-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_dragqueen_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('dragqueen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.dragqueen')),
            ],
        ),
    ]
